name: GitHub Actions - Document Hooks
inputs:
  output-file:
    description: Relative file path in the repository for Hooks output
    required: true
    default: 'docs/Hooks.md'
  source-directories:
    description: Directories to search for hooks
    required: true
    default: 'src/'
  main-branch:
    description: The main branch of the repository
    default: main

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      
    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

    - name: Install composer dependencies
      uses: php-actions/composer@v6
      with:
        dev: no
        interaction: no
        args: --no-scripts --ignore-platform-reqs 
