name: Branch Type to Label
description: Set PR labels according to the branch name.

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - uses: actions-ecosystem/action-add-labels@v1
      if: ${{ startsWith(github.head_ref, 'add/') }}
      with:
        labels: |
          type: enhancement
          changelog: add
    - uses: actions-ecosystem/action-add-labels@v1
      if: ${{ startsWith(github.head_ref, 'fix/') }}
      with:
        labels: |
          type: bug
          changelog: fix
    - uses: actions-ecosystem/action-add-labels@v1
      if: ${{ startsWith(github.head_ref, 'update/') || startsWith(github.head_ref, 'remove/') }}
      with:
        labels: |
          changelog: update
    - uses: actions-ecosystem/action-add-labels@v1
      if: ${{ startsWith(github.head_ref, 'tweak/') || startsWith(github.head_ref, 'dev/') }}
      with:
        labels: |
          changelog: tweak
    - uses: actions-ecosystem/action-add-labels@v1
      if: ${{ startsWith(github.head_ref, 'release/') }}
      with:
        labels: |
          changelog: none
