name: GitHub Actions - Create Release

on:
  push:

jobs:
  GetPluginReleases:
    name: Get Plugin Releases
    runs-on: ubuntu-latest
    steps:
      - name: Get Release versions from WooCommerce
        id: wc-versions
        uses: woocommerce/grow/get-plugin-releases@actions-v1
        with:
          slug: woocommerce

      - name: Get Release versions from WordPress
        id: wp-versions
        uses: woocommerce/grow/get-plugin-releases@actions-v1
        with:
          slug: wordpress

      - name: Get Release versions from GLA
        id: gla-versions
        uses: woocommerce/grow/get-plugin-releases@actions-v1
        with:
          slug: google-listings-and-ads

      - name: Get L-5 Release versions from WC including RC and Patches
        id: wc-versions-l5-rc
        uses: woocommerce/grow/get-plugin-releases@actions-v1
        with:
          slug: woocommerce
          releases: 5
          includeRC: true
          includePatches: true

      - name: Get L-5 Release versions from WC including only patches
        id: wc-versions-patches
        uses: woocommerce/grow/get-plugin-releases@actions-v1
        with:
          slug: woocommerce
          releases: 5
          includePatches: true
          
      - name: Show the versions output
        run: |
          echo "The versions WooCommerce are: ${{ steps.wc-versions.outputs.versions }}"
          echo "The versions Wordpress are: ${{ steps.wp-versions.outputs.versions }}."
          echo "The versions GLA are: ${{ steps.gla-versions.outputs.versions }}."
          echo "The versions WC RC are: ${{ steps.wc-versions-l5-rc.outputs.versions }}."
          echo "The versions WC ( inc patches ) are: ${{ steps.wc-versions-patches.outputs.versions }}."
